---
# - name: Install Docker
#   hosts:
#     - manager
#     - servers
#   remote_user: root
#   tasks:
#     - name: Install Docker on CentOS 7
#       include: ./docker/centos.yml
#       when: (ansible_facts['distribution'] == "CentOS")

#     - name: Install Docker on Ubuntu
#       include: ./docker/ubuntu.yml
#       when: (ansible_facts['distribution'] == "Ubuntu")

#   handlers:
#     - name: restart docker
#       service:
#         name: docker
#         state: restarted

# ------------------------------------------------------------------------------

# - name: Build Docker Swarm Cluster
#   hosts:
#     - manager
#     - servers
#   remote_user: root
#   tasks:
#     - name: Setup a Docker Swarm Manager
#       include: ./dockerswarm/manager.yml
#       when: "'manager' in group_names"
#     - name: Register dummy host with Token Variable
#       add_host:
#         name: "DUMMY_HOST"
#         TOKEN: "{{SWARM['swarm_facts']['JoinTokens']['Manager']}}"
#       when: "'manager' in group_names"

#     - name: Setup a Docker Swarm Worker
#       include: ./dockerswarm/worker.yml
#       when: "'servers' in group_names"

# ------------------------------------------------------------------------------

# - name: Install Nginx on manager
#   hosts:
#     - manager
#   remote_user: root
#   tasks:
#     # - name: Install Nginx on Ubuntu
#     #   include: ./nginx/install.yml
#     #   when: (ansible_facts['distribution'] == "Ubuntu")
    
#     # - name: Create Keys and Passwords for Nginx on Ubuntu
#     #   include: ./nginx/auth.yml
#     #   when: (ansible_facts['distribution'] == "Ubuntu")
    
#     - name: Configure Nginx  
#       include: ./nginx/config.yml
#       when: (ansible_facts['distribution'] == "Ubuntu")
    
#   handlers:
#     - name: Start Nginx
#       service:
#         name: nginx
#         state: started

#     - name: Restart Nginx
#       service:
#         name: nginx
#         state: restarted

- name: Build Docker Images
  hosts:
    - manager
  remote_user: root
  tasks:
    - name: Give insecure permissions to an existing directory
      ansible.builtin.file:
        path: /home/ubuntu/ansible-project/app/files
        state: directory
        recurse: yes
        owner: root
        group: root
        mode: '777'  

    - name: Create Mag Docker Image 
      include: ./app/mag.yml
    - name: this is debug
      debug:
        msg: "This is Login Results {{RESULTS['login_results']}}"
    - name: Create Blog Docker Image 
      include: ./app/blog.yml

    - name: Create Docker Swarm stack
      include: ./app/stack.yml 
   
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted



...