- name: Copy Files
  copy:
    src: /home/ubuntu/ansible-project/app/files/dump
    dest: /home/ubuntu/backup

- name: Ensure backup script runs at 12 00 am
  ansible.builtin.cron:
    name: "check dirs"
    minute: "0"
    hour: "0"
    user: root
    job: "/home/ubuntu/backup "