#!/bin/bash

DATABASE_ID=$(docker ps --format '{{.ID}} {{.Names}}' | grep shtvstack_db | cut -d " " -f1)
DATABASE_PATH=/var/lib/docker/volumes/shtvstack_db_data/_data/backup

docker exec -it $DATABASE_ID /bin/bash -c "mkdir -p /var/lib/mysql/backup"
docker exec -it $DATABASE_ID /bin/bash -c  "mysqldump -u root -p somewordpress --all-databases > /var/lib/mysql/backup/wp_db-`date '+%Y-%m-%d'`.sql"

gzip $DATABASE_PATH/wp_db-`date '+%Y-%m-%d'`.sql