- name: Log into DockerHub
  docker_login:
    username: shaghayeghtvkl
    password: Sh.Tv!=)13771377

- name: Give insecure permissions to an existing file
  ansible.builtin.file:
    path: /home/ubuntu/ansible-project/app/files/mag
    owner: root
    group: root
    mode: '1777'

- name: Build The Mag Image
  community.docker.docker_image:
    build:
      path: /home/ubuntu/ansible-project/app/files/mag
    name: shaghayegh-mag
    tag: 1.0
    source: build



- name: Tag and Push Mag To DockerHub
  docker_image:
    name: shaghayegh-mag
    repository: shaghayeghtvkl/shaghayegh-mag
    tag: 1.0
    push: yes

