# - name: Install pip
#   package:
#     name: python-pip
#     update_cache: yes
#     state: present
# - name: Install python-setuptools
#   package:
#     name: python-setuptools
#     update_cache: yes
#     state: present
# - name: Install jsondiff
#   pip:
#     name: jsondiff
#     state: present
# - name: Install pyyaml
#   pip:
#     name: pyyaml
#     state: present
- name: Log into DockerHub
  docker_login:
    username: shaghayeghtvkl
    password: Sh.Tv!=)13771377

- name: Merge node labels and new labels
  community.docker.docker_node:
    hostname: "server-1"
    labels:
      wp: true

- name: Merge node labels and new labels
  community.docker.docker_node:
    hostname: "server-2"
    labels:
      wp: true


- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: shtvstack
    compose:
      - /home/ubuntu/docker/docker-compose.yml