# - name: Install pip
#   package:
#     name: python-pip
#     update_cache: yes
#     state: present
# - name: Install python-setuptools
#   package:
#     name: python-setuptools
#     update_cache: yes
#     state: present
# - name: Install jsondiff
#   pip:
#     name: jsondiff
#     state: present
# - name: Install pyyaml
#   pip:
#     name: pyyaml
#     state: present
- name: Log into DockerHub
  docker_login:
    username: shaghayeghtvkl
    password: Sh.Tv!=)13771377

- name: Merge node labels and new labels
  docker_node:
    hostname: "{{item}}"
    labels:
      wp: true
    with_items:
      - server-1
      - server-2


- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: shtvstack
    compose:
      - /home/ubuntu/docker/docker-compose.yml