- name: "create www directory"
  file:
    path: /var/www/domain.com
    state: directory
    mode: "0775"
    owner: "root"
    group: "root"

- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: copy nginx site.conf
  template:
    src: ./config/site.conf.j2
    dest: /etc/nginx/sites-enabled/domain.com
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted